src/apps/discussions/urls.py
from discussions.views.discussions_actions_views import (
    ClosedDiscussionsView,
    CreateDiscussionView,
)
from discussions.views.discussions_detail_views import (
    DiscussionDetailView,
    DiscussionListView,
)
from django.urls import path

app_name = "discussions"

urlpatterns = [
    path("", DiscussionListView.as_view(), name="discussion_list"),
    path(
        "<uuid:discussion_id>/",
        DiscussionDetailView.as_view(),
        name="discussion_detail",
    ),
    path("create/", CreateDiscussionView.as_view(), name="create_discussion"),
    path("closed/", ClosedDiscussionsView.as_view(), name="closed_discussions"),
]

src/apps/posts/urls.py
from django.urls import path
from posts.views import action_on_the_post_views, all_posts_views, like_posts_views

app_name = "posts"

urlpatterns = [
    path("", all_posts_views.AllUserPostsView.as_view(), name="all_user_posts"),
    path(
        "create/",
        action_on_the_post_views.CreateUserPostView.as_view(),
        name="create_post",
    ),
    path(
        "edit/<uuid:post_id>/",
        action_on_the_post_views.EditUserPostView.as_view(),
        name="edit_post",
    ),
    path(
        "like/<uuid:post_id>/",
        like_posts_views.LikePostView.as_view(),
        name="like_post",
    ),
]

src/apps/rooms/urls.py
from django.urls import path
from rooms.views.all_rooms_views import AllRoomsView
from rooms.views.room_views import RoomView

app_name = "rooms"

urlpatterns = [
    path("", AllRoomsView.as_view(), name="rooms"),
    path("<slug:slug>/", RoomView.as_view(), name="room"),
]

src/apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from users.views import authentication_views, profile_views

app_name = "users"

urlpatterns = [
    path(
        "registration/",
        authentication_views.UserRegistrationView.as_view(),
        name="registration",
    ),
    path("login/", authentication_views.UserLoginView.as_view(), name="login"),
    path(
        "profile/<uuid:pk>",
        login_required(profile_views.UserProfileView.as_view()),
        name="profile",
    ),
    path(
        "profile/edit/<uuid:pk>/",
        login_required(profile_views.UserProfileEditView.as_view()),
        name="profile_edit",
    ),
    path("logout/", authentication_views.user_logout, name="logout"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.core.views import home

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("rooms/", include("rooms.urls")),
    path("discussions/", include("discussions.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/core/models.py
import uuid

from django.db import models
from versatileimagefield.fields import VersatileImageField


class BaseModel(models.Model):
    """Basic Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ("-date_added",)

src/apps/core/views.py
from discussions.models.discussion import Discussion
from django.db.models import Count
from django.shortcuts import render
from posts.models.post import UserPost


def home(request):
    top_posts = UserPost.objects.annotate(like_count=Count("likes")).order_by(
        "-like_count"
    )[:10]

    open_discussions = Discussion.objects.filter(closed=False)

    context = {
        "top_posts": top_posts,
        "open_discussions": open_discussions,
    }

    return render(request, "core/home.html", context)

src/apps/core/templates/base.html
<!DOCTYPE html>
<html style="height: 100%;">
<head>
    <style>

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        nav ul {
            list-style: none;
            padding: 0;
            display: flex;
        }

        nav ul li {
            margin-left: 20px;
        }

        nav ul li:first-child {
            margin-left: 0;
        }

        nav ul li a {
            text-decoration: none;
            color: #fff;
        }

        .site-title {
            font-size: 24px;
            font-weight: bold;
        }

        .logout-button {
            text-decoration: none;
            color: #fff;
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        .button {
            text-decoration: none;
            color: #fff;
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1 class="site-title">Chess Forum</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rooms:rooms' %}">Chats</a></li>
            {% endif %}
                <li><a href="{% url 'posts:all_user_posts' %}" class="button">All Posts</a></li>
                <li><a href="{% url 'discussions:discussion_list' %}" class="button">Discussions</a></li>

            {% if user.is_authenticated %}
                <li><a href="{% url 'users:profile' user.id %}">Profile</a></li>
                <li><a href="{% url 'users:login' %}" class="login-button">Logout</a></li>
            {% else %}
                <li><a href="{% url 'users:login' %}" class="login-button">Login</a></li>
                <li><a href="{% url 'users:registration' %}" class="registration-button">Registration</a></li>
            {% endif %}
    </header>
    <div>
        {% block content %}{% endblock %}
    </div>

    {% block scripts %}
        {% endblock %}

    <footer>
        &copy; 2023 Chess Forum.
    </footer>

</body>
</html>