src/apps/discussions/urls.py
from discussions.views.discussions_actions_views import (
    ClosedDiscussionsView,
    CreateDiscussionView,
)
from discussions.views.discussions_detail_views import (
    DiscussionDetailView,
    DiscussionListView,
)
from django.urls import path

app_name = "discussions"

urlpatterns = [
    path("", DiscussionListView.as_view(), name="discussion_list"),
    path(
        "<uuid:discussion_id>/",
        DiscussionDetailView.as_view(),
        name="discussion_detail",
    ),
    path("create/", CreateDiscussionView.as_view(), name="create_discussion"),
    path("closed/", ClosedDiscussionsView.as_view(), name="closed_discussions"),
]

src/apps/posts/urls.py
from django.urls import path
from posts.views import action_on_the_post_views, all_posts_views, like_posts_views

app_name = "posts"

urlpatterns = [
    path("", all_posts_views.AllUserPostsView.as_view(), name="all_user_posts"),
    path(
        "create/",
        action_on_the_post_views.CreateUserPostView.as_view(),
        name="create_post",
    ),
    path(
        "edit/<uuid:post_id>/",
        action_on_the_post_views.EditUserPostView.as_view(),
        name="edit_post",
    ),
    path(
        "like/<uuid:post_id>/",
        like_posts_views.LikePostView.as_view(),
        name="like_post",
    ),
]

src/apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from users.views import authentication_views, profile_views

app_name = "users"

urlpatterns = [
    path(
        "registration/",
        authentication_views.UserRegistrationView.as_view(),
        name="registration",
    ),
    path("login/", authentication_views.UserLoginView.as_view(), name="login"),
    path(
        "profile/<uuid:pk>",
        login_required(profile_views.UserProfileView.as_view()),
        name="profile",
    ),
    path(
        "profile/edit/<uuid:pk>/",
        login_required(profile_views.UserProfileEditView.as_view()),
        name="profile_edit",
    ),
    path("logout/", authentication_views.user_logout, name="logout"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.core.views import home

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("rooms/", include("rooms.urls")),
    path("discussions/", include("discussions.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/core/models.py
import uuid

from django.db import models
from versatileimagefield.fields import VersatileImageField


class BaseModel(models.Model):
    """Basic Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ("-date_added",)

src/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

from users.models.user import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "placeholder": "Enter a name"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "placeholder": "Enter your last name"})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "placeholder": "Enter a username"})
    )
    email = forms.CharField(
        widget=forms.EmailInput(attrs={"class": "form-control py-4", "placeholder": "Enter your email address"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control py-4", "placeholder": "Password"})
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control py-4", "placeholder": "Confirm password"})
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "placeholder": "Enter a username"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control py-4", "placeholder": "Password"})
    )

    class Meta:
        model = User
        fields = ["username", "password"]


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True}))
    email = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True}))
    telegram_id = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    chess_profile_url = forms.URLField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))

    class Meta:
        model = User
        fields = ("first_name", "last_name", "photo", "username", "email", "telegram_id", "chess_profile_url")

src/apps/users/forms/authentication_forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models.user import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-4", "placeholder": "Enter a name"}
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-4", "placeholder": "Enter your last name"}
        )
    )
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-4", "placeholder": "Enter a username"}
        )
    )
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control py-4",
                "placeholder": "Enter your email address",
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Password"}
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Confirm password"}
        )
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control py-4", "placeholder": "Enter a username"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control py-4", "placeholder": "Password"}
        )
    )

    class Meta:
        model = User
        fields = ["username", "password"]

src/apps/users/forms/profile_forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from users.models.user import User


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True})
    )
    bio = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control py-4"}))
    email = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4", "readonly": True})
    )
    telegram_id = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )
    chess_profile_url = forms.URLField(
        widget=forms.TextInput(attrs={"class": "form-control py-4"})
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "photo",
            "username",
            "bio",
            "email",
            "telegram_id",
            "chess_profile_url",
        )

src/apps/core/views.py
from discussions.models.discussion import Discussion
from django.db.models import Count
from django.shortcuts import render
from posts.models.post import UserPost


def home(request):
    top_posts = UserPost.objects.annotate(like_count=Count("likes")).order_by(
        "-like_count"
    )[:10]

    open_discussions = Discussion.objects.filter(closed=False)

    context = {
        "top_posts": top_posts,
        "open_discussions": open_discussions,
    }

    return render(request, "core/home.html", context)

src/apps/users/views.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView


from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.utils.decorators import method_decorator


from users.forms import RegistrationForm, LoginForm, UserProfileForm
from users.models import User
from posts.models import UserPost


class UserLoginView(LoginView):
    template_name = "users/login.html"
    form_class = LoginForm

    def get_success_url(self):
        user = self.request.user
        return reverse_lazy("users:profile", kwargs={"pk": user.id})


class UserRegistrationView(CreateView):
    model = User
    form_class = RegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"

    def get_object(self, queryset=None):
        user_id = self.kwargs.get('pk')
        return get_object_or_404(User, id=user_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_posts = UserPost.objects.filter(user=self.object)
        context['user_posts'] = user_posts
        return context

class UserProfileEditView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/profile_edit.html"

    def get_success_url(self):
        return reverse_lazy("users:profile", args=(self.object.id,))

    def get_object(self, queryset=None):
        user_id = self.kwargs.get('pk')
        if self.request.user.is_authenticated and user_id == self.request.user.id:
            return get_object_or_404(User, id=user_id)
        raise Http404("You are not authorized to edit this profile.")


def user_logout(request):
    logout(request)
    return redirect("login")

src/apps/users/views/authentication_views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from users.forms.authentication_forms import LoginForm, RegistrationForm
from users.models.user import User


class UserLoginView(LoginView):
    """
    View for user login.

    Attributes:
        template_name (str): The template used for displaying the login form.
        form_class (LoginForm): The form used for user login.

    Methods:
        get_success_url(self): Determines the URL to redirect after successful login.

    Template:
        users/login.html
    """

    template_name = "users/login.html"
    form_class = LoginForm

    def get_success_url(self):
        """
        Determines the URL to redirect after successful login.

        Returns:
            str: The URL to redirect to.
        """
        user = self.request.user
        return reverse_lazy("users:profile", kwargs={"pk": user.id})


class UserRegistrationView(CreateView):
    """
    View for user registration.

    Attributes:
        model (User): The User model.
        form_class (RegistrationForm): The form used for user registration.
        template_name (str): The template used for displaying the registration form.
        success_url (str): The URL to redirect after successful registration.

    Template:
        users/register.html
    """

    model = User
    form_class = RegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")


def user_logout(request):
    """
    View for user logout.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponseRedirect: Redirects to the login page after logout.
    """
    logout(request)
    return redirect("login")

src/apps/users/views/profile_views.py
from discussions.models.discussion import Discussion
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from posts.models.post import UserPost
from users.forms.profile_forms import UserProfileForm
from users.models.user import User
from users.services.user_service import UserService


class UserProfileView(UpdateView):
    """
    View for displaying a user's profile.

    Attributes:
        model (User): The User model.
        form_class (UserProfileForm): The form used for editing the profile.
        template_name (str): The template used for displaying the profile.

    Methods:
        get_object(self, queryset=None): Retrieves the user object to be displayed.
        get_context_data(self, **kwargs): Adds user's posts, liked posts, and discussions to the context.

    Template:
        users/profile.html
    """

    model = User
    form_class = UserProfileForm
    template_name = "users/profile.html"

    def get_object(self, queryset=None):
        """
        Retrieves the user object to be displayed.

        Args:
            queryset: The queryset to filter the user object.

        Returns:
            User: The user object.
        """
        user_id = self.kwargs.get("pk")
        return UserService.get_user_by_id(user_id)

    def get_context_data(self, **kwargs):
        """
        Adds additional context data to the view.

        Context:
            user_posts (QuerySet): User's posts.
            liked_posts (QuerySet): User's liked posts.
            user_discussions (QuerySet): User's discussions.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: The updated context data.
        """
        context = super().get_context_data(**kwargs)
        user_posts = UserPost.objects.filter(user=self.object)
        liked_posts = UserPost.objects.filter(likes__in=[self.object])
        user_discussions = Discussion.objects.filter(author=self.object)
        context["user_posts"] = user_posts
        context["liked_posts"] = liked_posts
        context["user_discussions"] = user_discussions
        return context


class UserProfileEditView(UpdateView):
    """
    View for editing a user's profile.

    Attributes:
        model (User): The User model.
        form_class (UserProfileForm): The form used for editing the profile.
        template_name (str): The template used for editing the profile.

    Methods:
        get_success_url(self): Determines the URL to redirect after successful profile editing.
        get_object(self, queryset=None): Retrieves the user object to be edited.

    Template:
        users/profile_edit.html
    """

    model = User
    form_class = UserProfileForm
    template_name = "users/profile_edit.html"

    def get_success_url(self):
        """
        Determines the URL to redirect after successful profile editing.

        Returns:
            str: The URL to redirect to.
        """
        return reverse_lazy("users:profile", args=(self.object.id,))

    def get_object(self, queryset=None):
        """
        Retrieves the user object to be edited.

        Checks if the user is authenticated and if the provided user ID matches the current user's ID.

        Args:
            queryset: The queryset to filter the user object.

        Returns:
            User: The user object.

        Raises:
            Http404: If the user is not authorized to edit this profile.
        """
        user_id = self.kwargs.get("pk")
        if self.request.user.is_authenticated and user_id == self.request.user.id:
            return UserService.get_user_by_id(user_id)
        raise Http404("You are not authorized to edit this profile.")

src/apps/core/templates/users/base.html
<!DOCTYPE html>
<html style="height: 100%;">
<head>
    <style>

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        nav ul {
            list-style: none;
            padding: 0;
            display: flex;
        }

        nav ul li {
            margin-left: 20px;
        }

        nav ul li:first-child {
            margin-left: 0;
        }

        nav ul li a {
            text-decoration: none;
            color: #fff;
        }

        .site-title {
            font-size: 24px;
            font-weight: bold;
        }

        .logout-button {
            text-decoration: none;
            color: #fff;
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        footer {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1 class="site-title">Chess Forum</h1>
        <nav>
            <ul>
                <li><a href="#">Chats</a></li>
                <li><a href="#">All Posts</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'users:profile' user.id %}">Profile</a></li>
                <li><a href="{% url 'users:login' %}" class="login-button">Logout</a></li>
            {% else %}
                <li><a href="{% url 'users:login' %}" class="login-button">Login</a></li>
                <li><a href="{% url 'users:registration' %}" class="registration-button">Registration</a></li>
            {% endif %}
    </header>
    <div>
        {% block content %}{% endblock %}
    </div>
    <footer>
        &copy; 2023 Chess Forum.
    </footer>
</body>
</html>

src/apps/core/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign In Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .signin-container {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .signin-container h2 {
            text-align: center;
        }

        .form-group {
            margin-bottom: 10px;
        }

        .form-group label {
            display: block;
            font-weight: bold;
        }

        .form-group input {
            width: 100%;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .btn-signin {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .btn-signin:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="signin-container">
        <h2>Sign In</h2>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-signin">Sign In</button>
            <h3>Don`t have an account?</h3>
            <a href="{% url 'users:registration' %}" class="login-button">Sign Up</a>
        </form>
    </div>
</body>
</html>

src/apps/core/templates/users/profile.html
{% extends "base.html" %}
{% load custom_filters %}
{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
        margin: 0;
        padding: 0;
    }

    h1 {
        text-align: center;
        color: #333;
        margin: 20px 0;
    }

    .profile-container {
        max-width: 800px;
        margin: 0 auto;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
        padding: 20px;
    }

    .profile-avatar {
        text-align: center;
        margin-bottom: 20px;
    }

    .profile-avatar img {
        max-width: 150px;
        max-height: 150px;
        border: 3px solid #ccc;
        border-radius: 50%;
    }

    .profile-info p {
        margin: 10px 0;
        font-size: 16px;
    }

    .profile-info strong {
        font-weight: bold;
    }

    .profile-info a {
        text-decoration: none;
        color: #007bff;
    }

    .profile-info a:hover {
        text-decoration: underline;
    }

    .profile-info .btn {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        margin-right: 10px;
        text-decoration: none;
        font-size: 16px;
    }

    .profile-info .btn:hover {
        background-color: #0056b3;
    }

    .profile-posts {
        background-color: #f9f9f9;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }

    .post {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 20px;
    }

    .left {
        float: left;
    }

    .right {
        float: right;
    }

    .clear {
        clear: both;
    }
</style>

    <h1>Chess Forum - {{ user.username }} Profile</h1>
    <div class="profile-container">
        <div class="profile-info left">
            <div class="profile-avatar">
                <img 
                src="{% if user.photo %} {{ user.photo.url }} {% endif %} " 
                alt="User Avatar">
            </div>

            <p><strong>Nickname:</strong> {{ user.username }}</p>
            <p><strong>First Name:</strong> {{ user.first_name }}</p>
            <p><strong>Last Name:</strong> {{ user.last_name }}</p>
            
            {% if user.telegram_id %}
                <p><strong>Telegram ID:</strong> {{ user.telegram_id }}</p>
            {% endif %}
            
            {% if user.chess_profile_url %}
                <p><strong>Chess Profile:</strong> <a href="{{ user.chess_profile_url }}" target="_blank">{{ user.chess_profile_url }}</a></p>
            {% endif %}

            {% if user.bio %}
                <p><strong>Bio:</strong> {{ user.bio }}</p>
            {% endif %}
            
            {% if user.subscriber %}
                <p><strong>Subscriber:</strong> Yes</p>
            {% endif %}

            <p><strong>Joined:</strong> {{ user.date_joined }}</p>
            
        </div>

        {% if user == request.user %}
            <div class="profile-info left">
                <a href="{% url 'users:profile_edit' user.id %}" class="btn btn-primary">Edit Profile</a>
            </div>
            <div class="profile-info left">
                <a href="{% url 'posts:create_post' %}" class="btn btn-primary">Create Post</a>
            </div>
        {% endif %}
    


        <div class="profile-posts right">
            <h1>Posts:</h1>
            {% for post in user_posts %}
            <div class="post">
                <h3>{{ post.title }}</h3>
                {% if post.image %}
                    <p><strong>Image:</strong></p>
                    <img src="{{ post.image.first.image.url }}" alt="{{ post.title }}">
                {% endif %}

                {% if post.game_link %}
                    <p><strong>Game Link:</strong> <a href="{{ post.game_link }}" target="_blank">{{ post.game_link }}</a></p>
                {% endif %}
                <p><strong>Body:</strong> {{ post.body }}</p>
                <p><strong>Date:</strong> {{ post.date_added }}</p>
            

                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'posts:like_post' post.id %}">
                    {% csrf_token %}
                        <button type="submit">
                        {% if post|has_liked_post:user %}
                            Unlike
                        {% else %}
                            Like
                        {% endif %}
                        </button>
                    </form>
                {% endif %}

                <p><strong>Likes:</strong> {{ post.likes.count }}</p>
      
                {% if user == request.user %}
                    <a href="{% url 'posts:edit_post' post.id %}" class="btn btn-primary">Edit</a>
                {% endif %}

            </div>
            {% endfor %}
            <div class="profile-posts left">
                <h3>Liked Posts:</h3>
                {% for post in liked_posts %}
                <div class="post">
                    <h4>Title: {{ post.title }}</h4>
                    <p><a href="{% url 'users:profile' post.user.id %}">Profile of {{ post.user.username }}</a></p>
                </div>
                {% endfor %}
            </div>
            <div class="profile-posts left">
                <h3>Discussions:</h3>
                <ul>
                    {% for discussion in user_discussions %}
                    <li><a href="{% url 'discussions:discussion_detail' discussion.id %}">{{ discussion.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>


        </div>
        
        <div class="clear"></div>
    </div>
{% endblock %}

src/apps/core/templates/users/profile_edit.html
{% extends "base.html" %}

{% block content %}
<style>
    h1 {
        text-align: center;
        font-family: Arial, sans-serif;
        color: #333;
    }

    .profile-container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    .profile-info {
        background-color: #f9f9f9;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .profile-avatar {
        text-align: center;
        margin-bottom: 20px;
    }

    .profile-avatar img {
        max-width: 150px;
        max-height: 150px;
        border: 1px solid #ccc;
        border-radius: 50%;
    }

    .profile-posts {
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }

    .post {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 20px;
    }

    .left {
        float: left;
    }

    .right {
        float: right;
    }

    .clear {
        clear: both;
    }
</style>
<h1>Edit Profile - {{ user.username }}</h1>
<div class="profile-container">
    <div class="profile-info left">
        <div class="profile-avatar">
            <img 
            src="{% if user.photo %} {{ user.photo.url }} {% endif %} " 
            alt="User Avatar">
        </div>
        <p><strong>Nickname:</strong> {{ user.username }}</p>
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>

        {% if user.telegram_id %}
            <p><strong>Telegram ID:</strong> {{ user.telegram_id }}</p>
        {% endif %}

        {% if user.chess_profile_url %}
            <p><strong>Chess Profile:</strong> <a href="{{ user.chess_profile_url }}" target="_blank">{{ user.chess_profile_url }}</a></p>
        {% endif %}

        {% if user.subscriber %}
            <p><strong>Subscriber:</strong> Yes</p>
        {% endif %}
    </div>

    <div class="profile-info left">
        <h2>Edit Profile</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Changes</button>
        </form>
    </div>

    <div class="clear"></div>
</div>
{% endblock %}

src/apps/core/templates/users/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .signup-container {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .signup-container h2 {
            text-align: center;
        }

        .form-group {
            margin-bottom: 10px;
        }

        .form-group label {
            display: block;
            font-weight: bold;
        }

        .form-group input {
            width: 100%;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        .btn-signup {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        .btn-signup:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="signup-container">
        <h2>Sign Up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn-signup">Sign Up</button>
            <h3>Have an account?</h3>
            <a href="{% url 'users:login' %}" class="login-button">Sign In</a>
        </form>
    </div>
</body>
</html>