src/apps/discussions/urls.py
from discussions.views.discussions_actions_views import (
    ClosedDiscussionsView,
    CreateDiscussionView,
)
from discussions.views.discussions_detail_views import (
    DiscussionDetailView,
    DiscussionListView,
)
from django.urls import path

app_name = "discussions"

urlpatterns = [
    path("", DiscussionListView.as_view(), name="discussion_list"),
    path(
        "<uuid:discussion_id>/",
        DiscussionDetailView.as_view(),
        name="discussion_detail",
    ),
    path("create/", CreateDiscussionView.as_view(), name="create_discussion"),
    path("closed/", ClosedDiscussionsView.as_view(), name="closed_discussions"),
]

src/apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from users.views import authentication_views, profile_views

app_name = "users"

urlpatterns = [
    path(
        "registration/",
        authentication_views.UserRegistrationView.as_view(),
        name="registration",
    ),
    path("login/", authentication_views.UserLoginView.as_view(), name="login"),
    path(
        "profile/<uuid:pk>",
        login_required(profile_views.UserProfileView.as_view()),
        name="profile",
    ),
    path(
        "profile/edit/<uuid:pk>/",
        login_required(profile_views.UserProfileEditView.as_view()),
        name="profile_edit",
    ),
    path("logout/", authentication_views.user_logout, name="logout"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.core.views import home

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("rooms/", include("rooms.urls")),
    path("discussions/", include("discussions.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/core/models.py
import uuid

from django.db import models
from versatileimagefield.fields import VersatileImageField


class BaseModel(models.Model):
    """Basic Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ("-date_added",)

src/apps/discussions/models/discussion.py
from core.models import BaseModel
from django.db import models
from users.models.user import User
from versatileimagefield.fields import VersatileImageField


class Discussion(BaseModel):
    """
    A model representing a discussion.

    Attributes:
        title (str): The title of the discussion.
        text (str): The text content of the discussion.
        author (User): The user who authored the discussion.
        image (VersatileImageField): An optional image associated with the discussion.
        closed (bool): A flag indicating if the discussion is closed or not.

    Methods:
        __str__(): Returns the title of the discussion as a string.

    """

    title = models.CharField(max_length=255)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = VersatileImageField(null=True, blank=True, upload_to="images")
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

src/apps/discussions/models/reply.py
from core.models import BaseModel
from discussions.models.discussion import Discussion
from django.db import models
from users.models.user import User
from versatileimagefield.fields import VersatileImageField


class Reply(BaseModel):
    """
    A model representing a reply to a discussion.

    Attributes:
        discussion (Discussion): The discussion to which the reply belongs.
        text (str): The text content of the reply.
        author (User): The user who authored the reply.
        image (VersatileImageField): An optional image associated with the reply.

    Methods:
        __str__(): Returns a string representation of the reply.

    """

    discussion = models.ForeignKey(
        Discussion, on_delete=models.CASCADE, related_name="replies"
    )
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = VersatileImageField(null=True, blank=True, upload_to="images")

    def __str__(self):
        return f'Reply to "{self.discussion.title}"'

src/apps/discussions/models/reply_like.py
from core.models import BaseModel
from discussions.models.reply import Reply
from django.db import models
from users.models.user import User


class ReplyLike(BaseModel):
    """
    A model representing a like on a reply.

    Attributes:
        reply (Reply): The reply that received the like.
        user (User): The user who liked the reply.

    Methods:
        __str__(): Returns a string representation of the like.

    """

    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Like by {self.user.username} on Reply {self.reply.id}"

src/apps/discussions/forms/discussion_forms.py
from discussions.models.discussion import Discussion
from django import forms


class DiscussionForm(forms.ModelForm):
    class Meta:
        model = Discussion
        fields = ["title", "text", "image"]

src/apps/discussions/forms/reply_forms.py
from discussions.models.discussion import Discussion
from discussions.models.reply import Reply
from django import forms


class ReplyForm(forms.ModelForm):
    discussion_id = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Reply
        fields = ["text", "image"]

    def clean(self):
        cleaned_data = super().clean()
        discussion_id = cleaned_data.get("discussion_id")
        try:
            discussion = Discussion.objects.get(pk=discussion_id)
            if not discussion:
                raise forms.ValidationError("Discussion doesn't exist.")
            if discussion.closed:
                raise forms.ValidationError("This discussion is closed.")
        except Discussion.DoesNotExist as e:
            raise forms.ValidationError(f"Discussion doesn't exist: {e}")
        return cleaned_data

src/apps/discussions/forms/reply_like_forms.py
from django import forms


class ReplyLikeForm(forms.Form):
    reply_id = forms.UUIDField(widget=forms.HiddenInput())

src/apps/core/views.py
from discussions.models.discussion import Discussion
from django.db.models import Count
from django.shortcuts import render
from posts.models.post import UserPost


def home(request):
    top_posts = UserPost.objects.annotate(like_count=Count("likes")).order_by(
        "-like_count"
    )[:10]

    open_discussions = Discussion.objects.filter(closed=False)

    context = {
        "top_posts": top_posts,
        "open_discussions": open_discussions,
    }

    return render(request, "core/home.html", context)

src/apps/discussions/views/discussions_actions_views.py
from discussions.forms.discussion_forms import DiscussionForm
from discussions.services.discussion_service import DiscussionService
from django.shortcuts import redirect, render
from django.views import View


class CreateDiscussionView(View):
    """
    View for creating discussions.

    GET request:
    Renders a form to create a discussion.

    POST request:
    Processes the form data, creates a discussion, and redirects to the discussion list if the form is valid.
    """

    def get(self, request):
        form = DiscussionForm()
        return render(request, "discussions/create_discussion.html", {"form": form})

    def post(self, request):
        """
        Handles the POST request for creating discussions.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: Redirects to the discussion list on success or re-renders the form on failure.
        """
        if request.method == "POST":
            form = DiscussionForm(request.POST, request.FILES)
            if form.is_valid():
                DiscussionService.create_discussion(request.user, form.cleaned_data)
                return redirect("discussions:discussion_list")
        else:
            form = DiscussionForm()
        return render(request, "discussions/create_discussion.html", {"form": form})


class ClosedDiscussionsView(View):
    """
    View for displaying closed discussions.

    GET request:
    Retrieves and renders a list of closed discussions.
    """

    def get(self, request):
        closed_discussions = DiscussionService.get_closed_discussions()
        return render(
            request,
            "discussions/closed_discussions.html",
            {"closed_discussions": closed_discussions},
        )

src/apps/discussions/views/discussions_detail_views.py
from discussions.forms.reply_forms import ReplyForm
from discussions.forms.reply_like_forms import ReplyLikeForm
from discussions.services.discussion_service import DiscussionService
from discussions.services.reply_like_service import ReplyLikeService
from discussions.services.reply_service import ReplyService
from django.shortcuts import redirect, render
from django.views import View


class DiscussionListView(View):
    """
    View for displaying a list of discussions.

    GET request:
    Retrieves and renders a list of discussions.
    """

    def get(self, request):
        discussions = DiscussionService.get_all_discussions()
        return render(
            request, "discussions/discussion_list.html", {"discussions": discussions}
        )


class DiscussionDetailView(View):
    """
    View for displaying details of a discussion.

    GET request:
    Retrieves and renders the details of a specific discussion and its replies.

    POST request:
    Processes the form data to create a reply, toggle a reply like, or close the discussion (if authorized).
    """

    def get(self, request, discussion_id):
        discussion = DiscussionService.get_discussion_by_id(discussion_id)
        replies = ReplyService.get_replies_for_discussion(discussion)
        initial_data = {"discussion_id": discussion_id}
        reply_form = ReplyForm(initial=initial_data)
        return render(
            request,
            "discussions/discussion_detail.html",
            {"discussion": discussion, "replies": replies, "reply_form": reply_form},
        )

    def post(self, request, discussion_id):
        discussion = DiscussionService.get_discussion_by_id(discussion_id)
        replies = ReplyService.get_replies_for_discussion(discussion)

        if request.method == "POST":
            if "close_discussion" in request.POST and request.user == discussion.author:
                DiscussionService.close_discussion(discussion)
                return redirect("discussions:discussion_list")

            reply_form = ReplyForm(request.POST, request.FILES)
            if reply_form.is_valid():
                ReplyService.create_reply(
                    discussion, request.user, reply_form.cleaned_data
                )
                return redirect(
                    "discussions:discussion_detail", discussion_id=discussion_id
                )

            like_form = ReplyLikeForm(request.POST)
            if like_form.is_valid():
                reply_id = like_form.cleaned_data["reply_id"]
                reply_to_like = ReplyService.get_reply_by_id(reply_id)
                ReplyLikeService.toggle_like(request.user, reply_to_like)

        else:
            reply_form = ReplyForm()
            like_form = ReplyLikeForm()

        return render(
            request,
            "discussions/discussion_detail.html",
            {
                "discussion": discussion,
                "replies": replies,
                "reply_form": reply_form,
                "like_form": like_form,
            },
        )

src/apps/core/templates/discussions/closed_discussions.html
{% extends "base.html" %}

{% block content %}
  <h1>Closed Discussions</h1>
  <ul>
    {% for discussion in closed_discussions %}
      <li>
        <a href="{% url 'discussions:discussion_detail' discussion.id %}">{{ discussion.title }}</a>
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'discussions:discussion_list' %}">Back to Discussion List</a>
{% endblock %}

src/apps/core/templates/discussions/create_discussion.html
{% extends "base.html" %}

{% block content %}
  <h1>Create Discussion</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Discussion</button>
  </form>
  <a href="{% url 'discussions:discussion_list' %}">Back to Discussion List</a>
  
{% endblock %}

src/apps/core/templates/discussions/discussion_detail.html
{% extends "base.html" %}

{% block content %}


  <h1>Discussion title: {{ discussion.title }}</h1>
  Discussion author:
  <a href="{% url 'users:profile' discussion.author.id %}">
     {{ discussion.author }}
  </a>
  <p>Discussion text:{{ discussion.text }}</p>
  {% if discussion.image %}
    <img src="{{ discussion.image.url }}" alt="{{ discussion.title }}" />
  {% endif %}

  {% if user.is_authenticated %}
  {% if user == discussion.author and not discussion.closed %}
    <form method="post">
      {% csrf_token %}
      <button type="submit" name="close_discussion">Close discussion</button>
    </form>
  {% endif %}
{% endif %}

{% if not discussion.closed %}
  {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>Create Reply</h2>
      {{ reply_form.as_p }}
      <button type="submit">Submit Reply</button>
    </form>
  {% endif %}
  {% else %}
    <b>This discussion is closed and no further replies are allowed.</b>
  {% endif %}
  


  <hr>
  <h2>Replies</h2>
  {% if replies %}
    <ul>
      {% for reply in replies %}
        <li>
          <a href="{% url 'users:profile' reply.author.id %}">
            {{ reply.author }}
          </a>
          <br>
          {{ reply.text }}
          <br>
          {% if reply.image %}
            image:
            <br>
            <img src="{{ reply.image.url }}" alt="{{ reply.title }}" />
          {% endif %}
          <br>
          <span>Like Count: {{ reply.likes.count }}</span>
          {% if not discussion.closed %}
            <form method="post">
              {% csrf_token %}
              {% if user.is_authenticated %}
                  <input type="hidden" name="reply_id" value="{{ reply.id }}">
                  <button type="submit" name="like_reply">Like</button>
              {% endif %}
          </form>
          
          
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No replies yet.</p>
  {% endif %}
  <hr>
  <a href="{% url 'discussions:discussion_list' %}">Back to Discussion List</a>
</div>
{% endblock %}

src/apps/core/templates/discussions/discussion_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Discussion List</h1>
  <ul>
    {% for discussion in discussions %}
      <li>
        <a href="{% url 'discussions:discussion_detail' discussion.id %}">{{ discussion.title }}</a>
        {% if discussion.closed %}
          <span style="color: red;">(Closed)</span>
        {% else %}
        <span style="color: green;">(Active)</span>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% if user.is_authenticated %}
    <a href="{% url 'discussions:create_discussion' %}">Create Discussion</a>
  {% endif %}
  <a href="{% url 'discussions:closed_discussions' %}">Closed Discussions</a>
{% endblock %}