src/apps/rooms/urls.py
from django.urls import path
from rooms.views.all_rooms_views import AllRoomsView
from rooms.views.room_views import RoomView

app_name = "rooms"

urlpatterns = [
    path("", AllRoomsView.as_view(), name="rooms"),
    path("<slug:slug>/", RoomView.as_view(), name="room"),
]

src/apps/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from users.views import authentication_views, profile_views

app_name = "users"

urlpatterns = [
    path(
        "registration/",
        authentication_views.UserRegistrationView.as_view(),
        name="registration",
    ),
    path("login/", authentication_views.UserLoginView.as_view(), name="login"),
    path(
        "profile/<uuid:pk>",
        login_required(profile_views.UserProfileView.as_view()),
        name="profile",
    ),
    path(
        "profile/edit/<uuid:pk>/",
        login_required(profile_views.UserProfileEditView.as_view()),
        name="profile_edit",
    ),
    path("logout/", authentication_views.user_logout, name="logout"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from apps.core.views import home

urlpatterns = [
    path("", home, name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
    path("rooms/", include("rooms.urls")),
    path("discussions/", include("discussions.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/core/models.py
import uuid

from django.db import models
from versatileimagefield.fields import VersatileImageField


class BaseModel(models.Model):
    """Basic Model"""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ("-date_added",)

src/apps/rooms/models.py
from core.models import BaseModel
from django.db import models


class Room(BaseModel):
    """
    Model representing a chat room.

    Attributes:
        name (CharField): The name of the room (max length 30 characters).
        slug (SlugField): A unique identifier for the room in slug format.
        premium (BooleanField): A flag indicating whether the room is a premium room (default is False).

    """

    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)
    premium = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Room: {self.name}"

src/apps/rooms/models/room.py
from core.models import BaseModel
from django.db import models


class Room(BaseModel):
    """
    Model representing a chat room.

    Attributes:
        name (CharField): The name of the room (max length 30 characters).
        slug (SlugField): A unique identifier for the room in slug format.
        premium (BooleanField): A flag indicating whether the room is a premium room (default is False).

    """

    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)
    premium = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Room: {self.name}"

src/apps/core/views.py
from discussions.models.discussion import Discussion
from django.db.models import Count
from django.shortcuts import render
from posts.models.post import UserPost


def home(request):
    top_posts = UserPost.objects.annotate(like_count=Count("likes")).order_by(
        "-like_count"
    )[:10]

    open_discussions = Discussion.objects.filter(closed=False)

    context = {
        "top_posts": top_posts,
        "open_discussions": open_discussions,
    }

    return render(request, "core/home.html", context)

src/apps/rooms/views/all_rooms_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from rooms.services.room_service import RoomService


@method_decorator(login_required, name="dispatch")
class AllRoomsView(View):
    """
    View for displaying a list of all available rooms.

    Attributes:
        None

    Methods:
        get(self, request): Handles GET requests and renders the list of rooms.

    Template:
        room/rooms.html
    """

    def get(self, request):
        """
        Handles GET requests and renders the list of all available rooms.

        Retrieves a list of all rooms using the RoomService.

        Args:
            request (HttpRequest): The HTTP GET request object.

        Returns:
            HttpResponse: The rendered list of rooms.
        """
        rooms = RoomService.get_all_rooms()
        return render(request, "room/rooms.html", {"rooms": rooms})

src/apps/rooms/views/room_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from room_messages.models.message import Message
from rooms.services.room_service import RoomService


@method_decorator(login_required, name="dispatch")
class RoomView(View):
    """
    View for displaying a room's details.

    Attributes:
        None

    Methods:
        get(self, request, slug): Handles GET requests and renders the room details page.

    Template:
        room/room.html
    """

    def get(self, request, slug):
        """
        Handles GET requests and renders the room details page.

        Retrieves a room by its slug and retrieves the latest 25 messages for the room.

        Args:
            request (HttpRequest): The HTTP GET request object.
            slug (str): The slug of the room to display.

        Returns:
            HttpResponse: The rendered room details page.
        """
        room = RoomService.get_room_by_slug(slug)
        messages = Message.objects.filter(room=room)[0:25]
        return render(request, "room/room.html", {"room": room, "messages": messages})

src/apps/core/templates/room/room.html
{% extends "base.html" %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">{{ room.name }}</h1>
</div>

<div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-messages">


        {% for m in messages %} 
            time added: {{ m.date_added }}
            <a href="{% url 'users:profile' m.user.id %}">{{ m.user.username }}</a>
            : {{ m.content }}<br>
        {% endfor %}

        
    </div>
</div>

<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <form method="post" action="." class="flex">
        {% csrf_token %} 
        <input type="text" name="content" class="flex-1 mr-3" placeholder="Your message..." id="chat-message-input">
        <button 
            class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700"
            id="chat-message-submit"
        >Submit</button>
    </form>
</div>
{% endblock %}


{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    {% comment %} const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    ); {% endcomment %}

    const chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/' + roomName + '/'
    );
    



    chatSocket.onclose = function(e) {
        console.log('onclose')
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);

        if (data.message) {
            document.querySelector('#chat-messages').innerHTML += ('<b>' + data.username + '</b>: ' + data.message + '<br>');
        } else {
            alert('The message was empty!')
        }

        scrollToBottom();
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault()

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        console.log({
            'message': message,
            'username': userName,
            'room': roomName
        })

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }));

        messageInputDom.value = '';

        return false
    };

    /**
    * A function for finding the messages element, and scroll to the bottom of it.
    */
    function scrollToBottom() {
        let objDiv = document.getElementById("chat-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    // Add this below the function to trigger the scroll on load.
    scrollToBottom();
</script>
{% endblock %}

src/apps/core/templates/room/rooms.html
{% extends "base.html" %}


{% block content %}


  <h1>Rooms</h1>

  <ul>

    {% for room in rooms %}
      <li>
          <h2>Room: {{ room.name }}</h2>

            <a href="{% url 'rooms:room' room.slug %}">Join</a>

      </li>

    {% endfor %}
  </ul>

{% endblock %}